name: crazydaily_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: 1.0.13
  json_annotation: ^2.0.0
  fluttertoast: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/ic_go.png
  module:
    androidPackage: com.example.crazydailyflutter
    iosBundleIdentifier: com.example.crazydailyFlutter
